id = "fhir-shorthand"
name = "FHIR Shorthand"
description = "FHIR Shorthand (FSH) language support for Zed: syntax highlighting, bracket matching, and code outline for .fsh files."
version = "0.1.0"
schema_version = 1
authors = ["Sergej Suskov <sergej.suskov@gmail.com>"]
repository = "https://github.com/spilikin/zed-fhir-shorthand"

[grammars.fsh]
repository = "https://github.com/spilikin/tree-sitter-fsh"
rev = "1cf5e02d4b8be7fd810cb0ed4d77f7c682c333cd"
